//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenterCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCenterCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Experiment UniqueElnId=&quot;SAMPLE&quot; User=&quot;joe.amato&quot; Project=&quot;PROJ2017&quot; SchemaVersion=&quot;2.0&quot; TrackingId=&quot;3ce27795-0000-423b-87dd-cdf79fb5164f&quot; xsi:noNamespaceSchemaLocation=&quot;file:.\XML%20Import%20Schema%20-%20V3.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Process ProcessType=&quot;Purification&quot; TrackingId=&quot;f5314c70-e53d-4b5c-88bf-ffe1abe2b785&quot;&gt;
        ///    &lt;Stage StageType=&quot;DistillationOfProduct&quot; Comment=&quot;&quot; TrackingId=&quot;7b4b9a2c-82c4-45a1-ace1-923d59cfb9c3&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAMPLE {
            get {
                return ResourceManager.GetString("SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:template match=&quot;Experiment&quot;&gt;
        ///    &lt;svg width=&quot;800px&quot; height=&quot;1000px&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///      &lt;g id=&quot;experimentheader&quot; transform=&quot;translate(0,0)&quot;&gt;
        ///        &lt;text x=&quot;5&quot; y=&quot;40&quot; width=&quot;800&quot; style=&quot;font-family:arial;font-size:24px;text-anchor:start;&quot;&gt;MetaData Overview&lt;/text&gt;
        ///
        ///        &lt;text x=&quot;10&quot; y=&quot;70&quot; width=&quot;700&quot; style=&quot;font-family:arial;font-size:16px;text-anchor:start&quot;&gt;
        ///          ELN ID:
        ///        &lt;/te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string svg {
            get {
                return ResourceManager.GetString("svg", resourceCulture);
            }
        }
    }
}
